name: GitSign commit verification
description: This action verifies the PR commit using Gitsign.
on:
  # Skip verification for Mend Renovate bot commits
  push:
    branches: 
      - "*!renovate/**"
  pull_request:
    types: [reopened, ready_for_review, review_requested]
    branches:
      - "*!renovate/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  gitSignVerify:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    name: Verify commit
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - uses: chainguard-dev/actions/setup-gitsign@3e8a2a226fad9e1ecbf2d359b8a7697554a4ac6d # v1.5.10
      - shell: bash
        run: |
          gitsign verify --certificate-identity-regexp="^.*@gmail.com$" --certificate-oidc-issuer="https://github.com/login/oauth"