name: Lint GitHub Actions
on:
  push:
    branches: [master, main, develop, feature/**]
    paths:
      - ".github/zizmor.yml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
  pull_request:
    types: [reopened, ready_for_review, review_requested]
    branches: ["**"]
    paths:
      - ".github/zizmor.yml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Analyze actions
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      security-events: write # write permission to create security alerts with Zizmor
      # contents: read # only needed for private repos
      # actions: read # only needed for private repos
    steps:
      - uses: cycodelabs/cimon-action@1c3e30d508634b3f4a60b02843126c9f93944d80 # v0.9.4
        with:
            prevent: false
            report-process-tree: true
            apply-fs-events: true
            fail-on-error: true
      - name: Optimize Git config for CI
        run: |
          # Disable compression for faster network transfer.
          git config --global core.compression 0 
          # Turn off fsync
          git config --global core.fsync -all
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            .github/zizmor.yml
          sparse-checkout-cone-mode: false
          filter: "blob:none"
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          config: .github/zizmor.yml
      - name: Lint GitHub Actions
        uses: reviewdog/action-actionlint@83e4ed25b168066ad8f62f5afbb29ebd8641d982 # v1.69.1
      - name: Check GitHub Actions with 'actionlint'
        # Ref: https://github.com/rhysd/actionlint/blob/main/docs/usage.md#use-actionlint-on-github-actions
        # shellcheck is too noisy and disabled
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color -shellcheck=
        shell: bash
