name: Playwright Tests for eShop
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "src/ClientApp/**"
      - "tests/ClientApp.UnitTests/**"
      - ".github/workflows/pr-validation-maui.yml"
  pull_request:
    types: [reopened, ready_for_review, review_requested]
    branches: [main]
    paths-ignore:
      - "**.md"
      - "src/ClientApp/**"
      - "test/ClientApp.UnitTests/**"
      - ".github/workflows/pr-validation-maui.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Ref: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  contents: read

jobs:
  testPlaywright:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Optimize Git config for CI
        run: |
          # Disable compression for faster network transfer.
          git config --global core.compression 0 
          # Turn off fsync
          git config --global core.fsync -all
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          filter: "blob:none"
      - uses: actions/setup-dotnet@2016bd2012dba4e32de620c46fe006a3ac9f0602 # v5.0.1
        with:
          dotnet-version: "10.0.x"
          dotnet-quality: "preview"
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install .NET HTTPS Development Certificate
        # if: matrix.os == 'ubuntu-latest'
        run: |
          dotnet dev-certs https --clean
          dotnet dev-certs https --trust
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Run Playwright tests
        run: npx playwright test
        env:
          ESHOP_USE_HTTP_ENDPOINTS: 1
          USERNAME1: bob
          PASSWORD: Pass123$
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
