name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches: ["main"]
    paths:
      - ".github/zizmor.yml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"
  pull_request:
    types: [reopened, ready_for_review, review_requested]
    branches: ["**"]
    paths:
      - ".github/zizmor.yml"
      - ".github/workflows/**.yml"
      - ".github/workflows/**.yaml"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: Analyze with zizmor
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      security-events: write # write permission to create security alerts
      # contents: read # only needed for private repos
      # actions: read # only needed for private repos
    steps:
      - name: Optimize Git config for CI
        run: |
          # Disable compression for faster network transfer.
          git config --global core.compression 0 
          # Turn off fsync
          git config --global core.fsync -all
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          sparse-checkout: |
            .github/workflows
            .github/zizmor.yml
          sparse-checkout-cone-mode: false
          filter: "blob:none"
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
